### ISSUE TITLE
enex2sb: Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by wataash** [pastak/scrapbox-converter#16]
```hs
$ yarn global add enex2sb
$ enex2sb
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@babel/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/wsh/.config/yarn/global/node_modules/@babel/register/lib/cache.js:19:37)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

maybe `@babel/core` should be `dependencies`, not `devDependencies`.

**Comment by pastak** [comment]
thanks for your notice 😃
